### ISSUE TITLE
单元格合并问题

### ISSUE THREAD

**Issue by junchub** [alan-et/alanpoi#10]
![1655798098172](https://user-images.githubusercontent.com/55817898/174746826-cbe09c68-cfd5-40e5-b972-f54bc7dbeed7.jpg)
如何实现表格合并，主子表的这种

**Comment by yunjl1225** [comment]
这种支持吗？

**Comment by junchub** [comment]
好像不支持，只能用poi手写

**Comment by alan-et** [comment]
感谢你的持续关注，计划会在版本1.4.0加入此功能。

**Comment by alan-et** [comment]
你好，你的问题已经在版本1.3.7实现，请更新！
实现方式：通过注解属性autoMerge=true,这样程序会自动把这一列值按规则合并（比如一列有6行，值依次为AAABBB，那么系会自动合并AAA、BBB为两个单元格） 
@ExcelColumn(name = "值",autoMerge = true, align = Align.CENTER)

 <dependency>
      <groupId>com.alanpoi</groupId>
      <artifactId>alanpoi-analysis</artifactId>
      <version>1.3.7</version>
  </dependency>

**Comment by DimonHo** [comment]
> 1.3.7

感觉应该还要加个属性，存在多个列需要合并的时候，列与列之间应该有个父子关系才对，比如先按A列合并，B列在A列合并的基础上再合并。否则会出现下面这样的结构：
![image](https://user-images.githubusercontent.com/3371641/183056415-c959d0d3-6fdc-4e5f-8902-8cb818333f7a.png)
预期应该是：
![image](https://user-images.githubusercontent.com/3371641/183056218-fee07ba2-3c10-4ee7-ae17-63a1ea3e41d9.png)

另外，你这个合并好像没有基于整个sheet中的数据进行分组，而是按照顺序逐个遍历行进行合并的，感觉应该先对整体数据根据分组字段进行排序才对

**Comment by alan-et** [comment]
> 
“应该是在A列的基础上加个属性，存在多个列需要合并的时候，列与列之间应该按父子关系才对，比如先A列合并，B列在A列的基础上再合并” 这是个很好的建议，会在后续版本中考虑进去；

针对第二个建议，一般公共组件不会对业务数据进行排序以及打乱的，因此如果有需要，可以由使用方系统按照自己的业务需求排序即可

**Comment by alan-et** [comment]
> > 1.3.7
> 
> 应该是在A列的基础上加个属性，存在多个列需要合并的时候，列与列之间应该按父子关系才对，比如先A列合并，B列在A列的基础上再合并。原来会出现下面这样的结构： 应该是： ![图片](https://user-images.githubusercontent.com/3371641/183056415-c959d0d3-6fdc-4e5f-8902-8cb818333f7a.png) ![图片](https://user-images.githubusercontent.com/3371641/183056218-fee07ba2-3c10-4ee7-ae17-63a1ea3e41d9.png)
> 
> 另外，你这组根据整个数据表中的一些才对进行分组，按照顺序中的顺序处理数据行对进行整理，以便进行更好的操作，

‘应该是在A列的基础上加个属性，存在多个列需要合并的时候，列与列之间应该按父子关系才对，比如先A列合并，B列在A列的基础上再合并‘ 这是一个很好的建议，会在一个版本中考虑进去；

针对第二个建议，一般公共组件不会对业务数据进行示例以及打乱的，因此有需要，可以由使用方系统按照自己的业务需求示例

**Comment by alan-et** [comment]
> > 1.3.7
> 
> 应该是在A列的基础上加个属性，存在多个列需要合并的时候，列与列之间应该按父子关系才对，比如先A列合并，B列在A列的基础上再合并。原来会出现下面这样的结构： 应该是： ![图片](https://user-images.githubusercontent.com/3371641/183056415-c959d0d3-6fdc-4e5f-8902-8cb818333f7a.png) ![图片](https://user-images.githubusercontent.com/3371641/183056218-fee07ba2-3c10-4ee7-ae17-63a1ea3e41d9.png)
> 
> 另外，你这组根据整个数据表中的一些才对进行分组，按照中的处理数据行进行整理，以便更好地对操作进行，

'应该是在A列的基础上加个，存在多个列A需要合并的时候，列与列之间的属性应该按父子关系才对，比如先A列合并，B列在列基础上再合并'这是一个很好的建议，会在一个版本中考虑进去；

针对第二个建议，一般公共组件不会对业务数据进行排序以及打乱的，因此有需要，可以由使用方系统按照自己的业务需求排序即可
