### ISSUE TITLE
1.3.5版本直接导出返回的是文件，而不是Excel，是我的操作有问题么？

### ISSUE THREAD

**Issue by myreadhouse** [alan-et/alanpoi#11]
获取数据集合后直接返回的
ExcelExportUtil.export(excelList, FactoryStockOrderReportDto.class, request, response,fileName);

**Comment by myreadhouse** [comment]
不好意思，我找到原因了，是我自己的原因

**Comment by alan-et** [comment]
感谢你的使用与认可
