### ISSUE TITLE
ExcelConsumeInterface 接口的 validData 方法中Map<Serializable, Object> excelParam的作用是啥 

### ISSUE THREAD

**Issue by Lianwenlong** [alan-et/alanpoi#13]
ExcelConsumeInterface 接口的 validData 方法，
public void validData(String workbookId, List<ExcelSheetData> sheetDataList, Map<Serializable, Object> excelParam) {

    }
对数据进行校验。有没有实现类示例可以提供下。Map<Serializable, Object> excelParam 参数是用来做什么的

**Comment by alan-et** [comment]
感谢你的持续关注,Map<Serializable, Object> excelParam,这个参数是用于参数透传的，里面的数据就是调用asyncImport方法中的excelParam值，用于业务数据和底层的数据透传
